version: '3.9'

services:
    front_end:
        build: .
        container_name: DAST
        # ports:
        # - '8989:8989'
        depends_on:
            - BackEnd
        volumes:
          - "$HOME/.Xauthority:/root/.Xauthority:rw"
        environment:
          - DISPLAY=${DISPLAY}
        network_mode: host

    # BackEnd:
    #     build: .
    #     container_name: DASTBackEnd
    #     ports:
    #     - '8989:8989'
